tasks:
  - command: wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
  - command: dpkg -i packages-microsoft-prod.deb
  - command: apt-get update
  - command: apt-get install azure-functions-core-tools-3